name: find-pull-request

on:
  workflow_call:
    outputs:
      number:
        description: "The Pull Request number"
        value: ${{ jobs.find-pr.outputs.number }}
      sha:
        description: "The SHA of the commit associated with this PR"
        value: ${{ jobs.find-pr.outputs.sha }}

jobs:
  find-pr:
    runs-on: ubuntu-latest
    outputs:
      number: ${{ env.CI_PR_NUMBER }}
      sha: ${{ env.CI_PR_SHA }}
    steps:
      - name: Get GitHub environment variables
        id: get-env
        uses: FranzDiebold/github-env-vars-action@v2
      # - name: Find Pull Request
      #   id: find-pull-request
      #   uses: potiuk/get-workflow-origin@v1_5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     sourceRunId: ${{ github.event.workflow_run.id }}
