name: stuff-on-pr
on:
  pull_request_trigger:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub environment variables
        id: get-env
        uses: FranzDiebold/github-env-vars-action@v2
      - name: now-say-something
        run: echo "Hello world!"