name: trigger-comment
on:
  workflow_run:
    workflows:
      - trigger-book-build
    types:
      - requested
      - completed

jobs:
  find-pull-request:
    uses: ProjectPythia/cookbook-actions/.github/workflows/find-pull-request.yaml@main
  
  preview-comment:
    needs: find-pull-request
    uses: ProjectPythia/cookbook-actions/.github/workflows/preview-comment.yaml@main
    with:
      pull_request_number: ${{ needs.find-pull-request.outputs.number }}
      sha: ${{ needs.find-pull-request.outputs.sha }}